---
title: "logistic regression"
author: "Mengxi Tan"
date: "11/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(googlesheets4)
library(tidyverse)

# read any public google sheets
sheets_deauth()
```


```{r class}
# read the google sheets
election <- read_sheet("13NhlT-Oik5P4NOKRWwrJ7xZQlddFNk81HHEw9wkWglM")

# income: categorical variables for five different categories
# partisanship and dvote
# do we need to even jitter partisanship? just the dvote

ggplot(election, aes(partisanship, dvote)) + geom_jitter(height = 0.2) + geom_smooth(method = "lm", se = FALSE)

# linear regression
mod <- lm(data = election, dvote ~ partisanship)

# logistic regression
mod_logistic <- glm(data = election, dvote ~partisanship)

#map logistic regression, create log line in geom_smooth
ggplot(mod_logistic, aes(partisanship, dvote)) +
  geom_jitter(height = 0.2) +
  geom_smooth(method = "glm", method.args = list(family = "binomial"))

#We can see that the change in partisanship on the high end doesn't change dvote much, but change in partisanship on the low end has a larger effect. 

#Why doesn't the regression line approach zero? There are still 3 data points that responded as -1.5 partisanship and voted democrat, whereas if you look to the right (towards 1 on the log regression) there isn't a respondent that votes republican and is more than 3 for partisanship. 

```


